---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-debian-min-java-lts
    image: debian:8

provisioner:
  name: ansible
  playbooks:
    converge: ../java-lts-online/playbook.yml
  options:
    extra-vars:
      java_license_declaration: 'I accept the "Oracle Binary Code License Agreement for the Java SE Platform Products and JavaFX" under the terms at http://www.oracle.com/technetwork/java/javase/terms/license/index.html'
  lint:
    name: ansible-lint

scenario:
  name: debian-min-java-lts-online

verifier:
  name: testinfra
  directory: ../java-lts/tests
  lint:
    name: flake8
